### ISSUE TITLE
Yarn link is broken

### ISSUE THREAD

**Issue by rafaelpdemelo** [kevenleone/gh#3]
Hi Keven! 

I realized that the current version has a problem, the `yarn link` isn't working... I saw the message you left in the release to do the `yarn unlink `but it didn't work either... 

I'm leaving a suggestion here for future users and maybe even yourself if you want to tweak it somehow. 

Instead of using `Yarn Link`, use `npm link` inside the repository and inside the repository you're going to use the CLI type `npm link gitray`. 

That's it! Cheers!

**Comment by kevenleone** [comment]
@rafaelpdemelo readme changed :) 

Feel free to add more suggestions and pull requests whenever necessary, your opinion is very welcome \o/
